import { makeStyles } from "@material-ui/core/styles";

export const styles = makeStyles((theme) => ({
  gridContainer: {
    flexDirection: "row-reverse",
    flexWrap: "wrap",
    backgroundColor: "#FFFFFF",
    padding: "20px",
  },
  header: {
    flexDirection: "row",
  },
  printComponent: {
    margin: 0,
    width: "100%",
  },
  image: {
    maxWidth: "70%",
    maxHeight: "70%",
    display: "flex",
    top: "10%",
    zIndex: "99",
    paddingBottom: "10px",
  },
  heading: {
    display: " flex",
    justifyContent: " space-around",
    alignItems: " center",
    textAlign: " center",
    fontFamily: "Nunito",
    fontStyle: "bold",
    fontWeight: "500",
    fontSize: "20px",
    lineHeight: "48px",
    color: "Black",
  },
  totalAmount: {
    color: "Black",
    fontWeight: "bold",
    fontSize: "16px",
    borderRadius: "8px",
    fontFamily: "Nunito",
    fontStyle: "normal",
    textAlign: "center",
    border: "2px solid black",
    alignSelf: "flex-end",
    padding: "10px",
    marginRight: "40px",
    marginBottom: "120px",
  },
  signature: {
    color: "Black",
    fontWeight: "bold",
    fontSize: "16px",
    marginTop: "7.3%",
    fontFamily: "Nunito",
    fontStyle: "normal",
    textAlign: "center",
    alignSelf: "flex-end",
    maxWidth: "32%",
    marginBottom: "20px",
    paddingBottom: "10px",
  },
  managerText: {
    maxWidth: "36%",
    padding: "7px 0px 1px 0",
  },
  printButton: {
    "&:hover": {
      backgroundColor: "transparent !important",
    },
    textTransform: "none",
    color: "#808CA3",
    padding: 0,
    fontFamily: "Nunito",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: "14px",
    minWidth: "50px",
    height: "26px",
  },
}));
